#!/bin/bash
# Admiral Framework — Test Generator (QA-02)
# Generates test skeletons for new source files by parsing exported
# functions/classes (TypeScript) or function definitions (Bash) and
# emitting boilerplate test files with describe/it or assert blocks.
#
# Usage:
#   test_generator.sh [--json] [--dry-run] [--out-dir DIR] <file> [<file> ...]
#
# Flags:
#   --json        Emit machine-readable JSON summary on stdout
#   --dry-run     Print generated content to stdout instead of writing files
#   --out-dir DIR Write test files to DIR instead of conventional location
#   <file>        Source file(s) to generate tests for
#
# Exit codes:
#   0  All test files generated successfully
#   1  One or more files could not be processed
#   2  Hard error (bad arguments, missing dependency)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
OPT_JSON=false
OPT_DRY_RUN=false
OPT_OUT_DIR=""
SOURCE_FILES=()

parse_args() {
  while [ $# -gt 0 ]; do
    case "$1" in
      --json)     OPT_JSON=true ;;
      --dry-run)  OPT_DRY_RUN=true ;;
      --out-dir)
        shift
        if [ $# -eq 0 ]; then
          echo "ERROR: --out-dir requires an argument" >&2
          exit 2
        fi
        OPT_OUT_DIR="$1"
        ;;
      --*)
        echo "ERROR: Unknown flag: $1" >&2
        exit 2
        ;;
      *)
        SOURCE_FILES+=("$1")
        ;;
    esac
    shift
  done
}

# ---------------------------------------------------------------------------
# Derive conventional test file location
# ---------------------------------------------------------------------------
derive_test_path() {
  local source_file="$1"
  local out_dir="$2"

  local basename
  basename=$(basename "$source_file")
  local stem="${basename%.*}"
  local ext="${basename##*.}"
  local source_dir
  source_dir=$(dirname "$source_file")

  if [ -n "$out_dir" ]; then
    echo "${out_dir}/test_${stem}.${ext}"
    return
  fi

  # Conventional: <source_dir>/tests/test_<stem>.<ext>
  echo "${source_dir}/tests/test_${stem}.${ext}"
}

# ---------------------------------------------------------------------------
# Parse TypeScript: extract exported function/class names
# ---------------------------------------------------------------------------
parse_ts_exports() {
  local filepath="$1"

  # Extract: export function name, export async function name,
  #          export class name, export const name =
  grep -nE '^\s*export\s+(async\s+)?function\s+\w+|^\s*export\s+(default\s+)?class\s+\w+|^\s*export\s+const\s+\w+\s*[=:(]' \
    "$filepath" 2>/dev/null \
    | grep -oE '(function|class|const)\s+\w+' \
    | awk '{print $2}' \
    | sort -u \
    || true
}

# ---------------------------------------------------------------------------
# Generate TypeScript test skeleton
# ---------------------------------------------------------------------------
generate_ts_test() {
  local source_file="$1"

  local basename
  basename=$(basename "$source_file")
  local stem="${basename%.*}"

  # Compute relative import path from tests/ sibling to source
  local import_path="../${stem}"

  local exports
  exports=$(parse_ts_exports "$source_file")

  local export_list=""
  if [ -n "$exports" ]; then
    export_list=$(echo "$exports" | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')
  fi

  # Build describe/it blocks
  local test_blocks=""
  if [ -n "$exports" ]; then
    while IFS= read -r fn_name; do
      test_blocks+="
  describe('${fn_name}', () => {
    it('should handle the happy path', () => {
      // TODO: arrange
      // const result = ${fn_name}(/* args */);
      // assert.strictEqual(result, /* expected */);
      assert.ok(true, 'replace with real assertion');
    });

    it('should handle edge case: empty/null input', () => {
      // TODO: test boundary conditions
      assert.ok(true, 'replace with real assertion');
    });

    it('should handle edge case: invalid input throws', () => {
      // TODO: assert.throws(() => ${fn_name}(/* invalid */));
      assert.ok(true, 'replace with real assertion');
    });
  });
"
    done <<< "$exports"
  else
    test_blocks="
  it('should export expected symbols', () => {
    // TODO: import module and verify exports
    assert.ok(true, 'add real assertions');
  });
"
  fi

  cat <<EOF
// Admiral Framework — Auto-generated test skeleton for ${basename}
// Generated by QA-02 test_generator.sh
// Customize each TODO block before committing.
//
// Run: node --test ${stem}.test.ts  (or via npm test)

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
$([ -n "$export_list" ] && echo "import { ${export_list} } from '${import_path}';" || echo "// import { /* exports */ } from '${import_path}';")

describe('${stem}', () => {
${test_blocks}
});
EOF
}

# ---------------------------------------------------------------------------
# Parse Bash: extract function definitions
# ---------------------------------------------------------------------------
parse_sh_functions() {
  local filepath="$1"

  # Match: function_name() { or function function_name {
  grep -nE '^\s*[a-z_][a-z0-9_]*\s*\(\s*\)\s*\{|^\s*function\s+[a-z_][a-z0-9_]+\s*\{' \
    "$filepath" 2>/dev/null \
    | grep -oE '(function\s+)?[a-z_][a-z0-9_]+\s*(\(\s*\))?' \
    | grep -oE '^[a-z_][a-z0-9_]+' \
    | grep -v '^function$' \
    | sort -u \
    || true
}

# ---------------------------------------------------------------------------
# Generate Bash test skeleton
# ---------------------------------------------------------------------------
generate_sh_test() {
  local source_file="$1"

  local basename
  basename=$(basename "$source_file")
  local stem="${basename%.*}"

  # Resolve path from tests/ back to source
  local source_rel="../${basename}"

  local functions
  functions=$(parse_sh_functions "$source_file")

  # Build assert blocks
  local test_blocks=""
  if [ -n "$functions" ]; then
    while IFS= read -r fn_name; do
      test_blocks+="
# --- ${fn_name} ---

# Test: ${fn_name} happy path
# TODO: source the script and call ${fn_name} with valid input
# ACTUAL=\$(${fn_name} \"valid_arg\")
# assert_eq \"${fn_name}: happy path\" \"expected_output\" \"\$ACTUAL\"

# Test: ${fn_name} exit code
# EXIT_CODE=0
# ${fn_name} \"valid_arg\" > /dev/null 2>&1 || EXIT_CODE=\$?
# assert_exit_code \"${fn_name}: exits 0 on success\" 0 \"\$EXIT_CODE\"

# Test: ${fn_name} edge case (empty input)
# EXIT_CODE=0
# ${fn_name} \"\" > /dev/null 2>&1 || EXIT_CODE=\$?
# assert_exit_code \"${fn_name}: handles empty input\" 1 \"\$EXIT_CODE\"
"
    done <<< "$functions"
  else
    test_blocks="
# TODO: add test cases for functions in ${basename}
# ACTUAL=\$(some_function \"arg\")
# assert_eq \"some_function: basic\" \"expected\" \"\$ACTUAL\"
"
  fi

  cat <<EOF
#!/bin/bash
# Admiral Framework — Auto-generated test skeleton for ${basename}
# Generated by QA-02 test_generator.sh
# Customize each TODO block before committing.
#
# Run: bash ${stem}.test.sh  (or via make test)

set -euo pipefail

SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="\$(cd "\$SCRIPT_DIR/../../.." && pwd)"

source "\$SCRIPT_DIR/../../lib/assert.sh"

# Source the script under test
# shellcheck source=../${basename}
source "\$SCRIPT_DIR/${source_rel}"

echo "========================================"
echo " Test Suite: ${basename}"
echo "========================================"
echo ""

setup

# ---------------------------------------------------------------------------
# Generated test blocks
# ---------------------------------------------------------------------------
${test_blocks}

# ---------------------------------------------------------------------------
teardown
print_results "${stem} Tests"
EOF
}

# ---------------------------------------------------------------------------
# Result accumulator
# ---------------------------------------------------------------------------
RESULTS_JSON="[]"

add_result() {
  local source="$1"
  local test_path="$2"
  local status="$3"
  local message="$4"

  local entry
  entry=$(jq -n \
    --arg src   "$source" \
    --arg test  "$test_path" \
    --arg st    "$status" \
    --arg msg   "$message" \
    '{source: $src, test_file: $test, status: $st, message: $msg}')

  RESULTS_JSON=$(echo "$RESULTS_JSON" | jq --argjson e "$entry" '. + [$e]')
}

# ---------------------------------------------------------------------------
# Process a single source file
# ---------------------------------------------------------------------------
process_file() {
  local source_file="$1"

  # Resolve to absolute path
  if [ "${source_file:0:1}" != "/" ]; then
    source_file="${PROJECT_ROOT}/${source_file}"
  fi

  if [ ! -f "$source_file" ]; then
    add_result "$source_file" "" "error" "Source file not found"
    return 1
  fi

  local basename
  basename=$(basename "$source_file")
  local ext="${basename##*.}"

  local test_path
  test_path=$(derive_test_path "$source_file" "$OPT_OUT_DIR")

  local content=""

  case "$ext" in
    ts)
      content=$(generate_ts_test "$source_file")
      ;;
    sh)
      content=$(generate_sh_test "$source_file")
      ;;
    *)
      add_result "$source_file" "$test_path" "skip" "Unsupported file type: .$ext"
      return 0
      ;;
  esac

  if [ "$OPT_DRY_RUN" = true ]; then
    echo "# === Test skeleton for: $source_file ==="
    echo "# Would write to: $test_path"
    echo "$content"
    echo ""
    add_result "$source_file" "$test_path" "dry-run" "Content printed to stdout"
    return 0
  fi

  # Check if test file already exists
  if [ -f "$test_path" ]; then
    add_result "$source_file" "$test_path" "skip" "Test file already exists — not overwriting"
    return 0
  fi

  # Ensure output directory exists
  local test_dir
  test_dir=$(dirname "$test_path")
  mkdir -p "$test_dir"

  echo "$content" > "$test_path"
  add_result "$source_file" "$test_path" "created" "Test skeleton written"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
  parse_args "$@"

  if [ "${#SOURCE_FILES[@]}" -eq 0 ]; then
    echo "ERROR: No source files specified" >&2
    echo "Usage: test_generator.sh [--json] [--dry-run] [--out-dir DIR] <file> [<file> ...]" >&2
    exit 2
  fi

  local overall_status="pass"

  for f in "${SOURCE_FILES[@]}"; do
    if ! process_file "$f"; then
      overall_status="fail"
    fi
  done

  local timestamp
  timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u +%Y-%m-%dT%H:%M:%S.000Z)

  local created_count skip_count error_count
  created_count=$(echo "$RESULTS_JSON" | jq '[.[] | select(.status == "created")] | length' | tr -d '\r')
  skip_count=$(echo "$RESULTS_JSON"    | jq '[.[] | select(.status == "skip" or .status == "dry-run")] | length' | tr -d '\r')
  error_count=$(echo "$RESULTS_JSON"   | jq '[.[] | select(.status == "error")] | length' | tr -d '\r')

  if [ "$error_count" -gt 0 ]; then
    overall_status="fail"
  fi

  local report
  report=$(jq -n \
    --arg ts       "$timestamp" \
    --argjson res  "$RESULTS_JSON" \
    --argjson cr   "$created_count" \
    --argjson sk   "$skip_count" \
    --argjson er   "$error_count" \
    --arg status   "$overall_status" \
    '{generator: {
        timestamp:     $ts,
        results:       $res,
        created:       $cr,
        skipped:       $sk,
        errors:        $er,
        overall:       $status
      }}')

  if [ "$OPT_JSON" = true ]; then
    echo "$report"
  else
    echo "========================================"
    echo " Test Generator Report"
    echo "========================================"
    echo " Created : $created_count"
    echo " Skipped : $skip_count"
    echo " Errors  : $error_count"
    echo " Status  : $overall_status"
    echo "========================================"
    echo ""
    echo "$RESULTS_JSON" | jq -r '.[] | "  [\(.status | ascii_upcase)] \(.source)\n    -> \(.test_file)\n    \(.message)\n"'
  fi

  if [ "$overall_status" = "fail" ]; then
    exit 1
  fi
  exit 0
}

main "$@"
