#!/bin/bash
# generate_ground_truth.sh — Scaffold a blank Ground Truth document from templates.
#
# Usage: generate_ground_truth.sh [output_dir]
#   output_dir: Directory to write ground-truth.yaml (default: current directory)
#
# Produces a single ground-truth.yaml combining Mission, Boundaries, and
# Success Criteria templates. The human fills it in before fleet deployment.
#
# Exit codes: 0=success, 1=error
# Spec ref: Part 1 — Strategy Triangle
# SO ref: SO-15 (Pre-Work Validation)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_DIR="${SCRIPT_DIR}/templates"
OUTPUT_DIR="${1:-.}"

if [[ ! -d "${TEMPLATE_DIR}" ]]; then
  echo "ERROR: Template directory not found: ${TEMPLATE_DIR}" >&2
  exit 1
fi

for tmpl in mission.yaml boundaries.yaml success-criteria.yaml; do
  if [[ ! -f "${TEMPLATE_DIR}/${tmpl}" ]]; then
    echo "ERROR: Required template missing: ${TEMPLATE_DIR}/${tmpl}" >&2
    exit 1
  fi
done

mkdir -p "${OUTPUT_DIR}"

OUTPUT_FILE="${OUTPUT_DIR}/ground-truth.yaml"

if [[ -f "${OUTPUT_FILE}" ]]; then
  echo "ERROR: ${OUTPUT_FILE} already exists. Remove it first or choose a different directory." >&2
  exit 1
fi

cat > "${OUTPUT_FILE}" << 'HEADER'
# Admiral Ground Truth Document
# Generated by generate_ground_truth.sh
#
# This is the single source of strategic truth for your project.
# Fill in every field before deploying an Admiral fleet.
# Run validate_ground_truth.sh to check completeness.
#
# Spec ref: Part 1 — Strategy Triangle
# "If any vertex is missing, the fleet will infer one, and the inference
# will be subtly wrong."

version: "1.0"

project:
  name: ""
  repository: ""
  created: GENERATED_DATE
  last_reviewed: GENERATED_DATE

HEADER

# Replace the date placeholder
sed -i "s/GENERATED_DATE/$(date +%Y-%m-%d)/g" "${OUTPUT_FILE}"

# Append each template section
echo "mission:" >> "${OUTPUT_FILE}"
# Indent and append mission template (skip comment lines at top)
sed -n '/^[^#]/,$p' "${TEMPLATE_DIR}/mission.yaml" | sed 's/^/  /' >> "${OUTPUT_FILE}"
echo "" >> "${OUTPUT_FILE}"

echo "boundaries:" >> "${OUTPUT_FILE}"
sed -n '/^[^#]/,$p' "${TEMPLATE_DIR}/boundaries.yaml" | sed 's/^/  /' >> "${OUTPUT_FILE}"
echo "" >> "${OUTPUT_FILE}"

echo "success_criteria:" >> "${OUTPUT_FILE}"
sed -n '/^[^#]/,$p' "${TEMPLATE_DIR}/success-criteria.yaml" | sed 's/^/  /' >> "${OUTPUT_FILE}"

echo "Generated: ${OUTPUT_FILE}"
echo "Next step: Fill in all fields, then run validate_ground_truth.sh ${OUTPUT_FILE}"
