"""Convert monitor findings into Brain seed candidates.

The Brain stores what the Admiral needs to know. Each finding from the
monitor maps to a Brain entry category:

  CONTEXT — Snapshots of the world as it is right now.
    "Claude Opus 4.6 supports 200K context, native tool use, extended thinking."
    "MCP spec v2025-11 added streamable HTTP transport."
    The Admiral checks CONTEXT when choosing model tiers, configuring
    tool access, or understanding what's available.

  PATTERN — Reusable approaches that work.
    "Aider uses a diff-based edit format that reduces token cost by 40%."
    "Claude Code's prompt anatomy: identity → authority → constraints → task."
    The Admiral checks PATTERN when designing agent prompts, configuring
    fleet composition, or structuring workflows.

  LESSON — What experience has taught.
    "SWE-agent found that search-then-edit outperforms whole-file rewrite."
    "Repos with CLAUDE.md instructions produce 30% fewer agent errors."
    The Admiral checks LESSON when deciding between approaches.

IMPORTANT: All candidates pass through quarantine before Brain ingestion.
No raw external content is ever written directly to the Brain.
"""

from __future__ import annotations

import os
import re
from datetime import datetime, timezone

from .scanner import ScanResult, Finding


# Finding kind → Brain category mapping
_KIND_TO_BRAIN_CATEGORY = {
    "model_release": "context",       # What models can do right now
    "model_docs": "context",          # Official documentation content
    "exemplar_update": "pattern",     # How a leading tool changed its approach
    "practice_found": "pattern",      # New repo with fleet-relevant patterns
    "star_surge": "pattern",          # Community validates an approach
    "release": "context",             # General release info
    "new_repo": "context",            # General discovery
}


def write_seed_candidates(result: ScanResult, output_dir: str) -> str | None:
    """Generate a Python seed file from scan findings.

    Each entry maps to a brain_record() call with the appropriate
    category (CONTEXT, PATTERN, or LESSON). All require human review
    before planting.
    """
    if not result.has_findings:
        return None

    os.makedirs(output_dir, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    path = os.path.join(output_dir, f"seed-candidates-{today}.py")

    content = _render_seed_file(result, today)

    with open(path, "w") as f:
        f.write(content)

    return path


def _render_seed_file(result: ScanResult, date: str) -> str:
    """Render scan findings as Brain seed candidates."""
    lines = []

    lines.append(f'"""Brain seed candidates — {date}')
    lines.append(f"")
    lines.append(f"Generated by the AI Landscape Monitor.")
    lines.append(f"")
    lines.append(f"Each entry becomes a Brain record that the Admiral can query when")
    lines.append(f"deploying or updating a fleet. Review each for accuracy and relevance.")
    lines.append(f"")
    lines.append(f"Brain categories used:")
    lines.append(f"  CONTEXT — What models/tools can do right now (capabilities, APIs, specs)")
    lines.append(f"  PATTERN — How the best tools configure agents (prompts, tools, workflows)")
    lines.append(f"  LESSON  — What experience teaches (what works, what doesn't, trade-offs)")
    lines.append(f"")
    lines.append(f"To plant approved seeds:")
    lines.append(f"    python -m aiStrat.monitor.seed_writer --plant {date}")
    lines.append(f'"""')
    lines.append(f"")
    lines.append(f"from __future__ import annotations")
    lines.append(f"")
    lines.append(f'SESSION = "monitor-{date}"')
    lines.append(f'PROJECT = "fleet-admiral"')
    lines.append(f"")
    lines.append(f"CANDIDATES = [")

    for i, finding in enumerate(result.findings):
        entry = _finding_to_entry(finding)
        if entry:
            lines.append(f"    # ── {i+1}. [{entry['category'].upper()}] {finding.kind} ──")
            if entry.get("admiral_context"):
                lines.append(f"    # Admiral context: {entry['admiral_context']}")
            lines.append(f"    {{")
            lines.append(f'        "approved": False,')
            lines.append(f'        "project": PROJECT,')
            lines.append(f'        "category": {_safe_repr(entry["category"])},')
            lines.append(f'        "title": {_safe_repr(entry["title"])},')
            lines.append(f'        "content": {_safe_repr(entry["content"])},')
            lines.append(f'        "metadata": {{')
            lines.append(f'            "tags": {entry["tags"]!r},')
            lines.append(f'            "source": "ai-landscape-monitor",')
            lines.append(f'            "scan_date": "{date}",')
            if finding.url:
                lines.append(f'            "url": {_safe_repr(finding.url)},')
            if entry.get("relevance"):
                lines.append(f'            "relevance": {_safe_repr(entry["relevance"])},')
            lines.append(f"        }},")
            lines.append(f'        "source_agent": "monitor",')
            lines.append(f'        "source_session": SESSION,')
            lines.append(f"    }},")

    lines.append(f"]")
    lines.append(f"")
    lines.append(f"")
    lines.append(f"def get_approved():")
    lines.append(f'    """Return only approved candidates."""')
    lines.append(f'    return [c for c in CANDIDATES if c.get("approved")]')
    lines.append(f"")

    return "\n".join(lines)


def _finding_to_entry(finding: Finding) -> dict | None:
    """Convert a Finding to a Brain entry dict."""
    category = _KIND_TO_BRAIN_CATEGORY.get(finding.kind, "context")
    data = finding.data

    if finding.kind == "model_release":
        return _model_release_entry(finding, data)

    if finding.kind == "model_docs":
        return _model_docs_entry(finding, data)

    if finding.kind == "exemplar_update":
        return _exemplar_update_entry(finding, data)

    if finding.kind == "practice_found":
        return _practice_found_entry(finding, data)

    if finding.kind == "star_surge":
        return _star_surge_entry(finding, data)

    if finding.kind == "release":
        return _generic_release_entry(finding, data)

    if finding.kind == "new_repo":
        return _generic_repo_entry(finding, data)

    return {
        "category": category,
        "title": _sanitize_text(finding.title),
        "content": _sanitize_text(finding.body),
        "tags": [_sanitize_tag(t) for t in finding.tags],
    }


def _model_release_entry(finding: Finding, data: dict) -> dict:
    """Brain CONTEXT: What a model can do right now.

    The Admiral queries this when assigning model tiers to agent roles.
    """
    repo = data.get("repo", "unknown")
    tag = data.get("tag", "")
    release_body = data.get("full_release_body", finding.body)
    admiral_q = data.get("admiral_question", "")

    return {
        "category": "context",
        "title": _sanitize_text(f"Model release: {repo} {tag}"),
        "content": _sanitize_text(
            f"{repo} released {tag}.\n\n"
            f"Release notes:\n{release_body}"
        ),
        "tags": [_sanitize_tag(t) for t in finding.tags],
        "admiral_context": admiral_q,
    }


def _model_docs_entry(finding: Finding, data: dict) -> dict:
    """Brain CONTEXT: Official documentation for a model release.

    Full text from blog posts, docs pages, changelogs — the deep
    understanding of what changed and what it means for fleet config.
    """
    repo = data.get("repo", "unknown")
    tag = data.get("tag", "")
    full_content = data.get("full_content", finding.body)
    url = data.get("content_url", finding.url)
    admiral_q = data.get("admiral_question", "")

    return {
        "category": "context",
        "title": _sanitize_text(f"Official docs: {repo} {tag}"),
        "content": _sanitize_text(
            f"Source: {url}\n\n"
            f"{full_content}"
        ),
        "tags": [_sanitize_tag(t) for t in finding.tags],
        "admiral_context": admiral_q,
    }


def _exemplar_update_entry(finding: Finding, data: dict) -> dict:
    """Brain PATTERN: How a leading tool changed its agent design.

    When Claude Code, Aider, SWE-agent etc. update, the Admiral needs
    to know what changed in their approach — new prompt patterns, tool
    definitions, orchestration logic — to decide if the fleet should adapt.
    """
    repo = data.get("repo", "unknown")
    tag = data.get("tag", "")
    release_body = data.get("full_release_body", finding.body)
    watch_for = data.get("watch_for", [])

    watch_str = ""
    if watch_for:
        watch_str = (
            "\n\nReview this release for changes to: "
            + ", ".join(watch_for) + "."
        )

    return {
        "category": "pattern",
        "title": _sanitize_text(f"Exemplar update: {repo} {tag}"),
        "content": _sanitize_text(
            f"{repo} released {tag}.{watch_str}\n\n"
            f"Release notes:\n{release_body}"
        ),
        "tags": [_sanitize_tag(t) for t in finding.tags],
    }


def _practice_found_entry(finding: Finding, data: dict) -> dict:
    """Brain PATTERN: A repo demonstrating fleet-relevant agent design.

    Not just "popular repo" — this is a repo that shows how to configure
    agents, structure prompts, or manage SDLC workflows with LLMs.
    The Admiral should investigate it for patterns to adopt.
    """
    full_name = data.get("full_name", "unknown")
    stars = data.get("stars", 0)
    language = data.get("language", "unknown")
    relevance = data.get("relevance", "relevant")
    admiral_need = data.get("admiral_need", "")

    context_str = f"\n\nAdmiral context: {admiral_need}" if admiral_need else ""

    return {
        "category": "pattern",
        "title": _sanitize_text(f"Agent pattern: {full_name}"),
        "content": _sanitize_text(
            f"Discovered {full_name} ({stars:,} stars, {language}).\n\n"
            f"Description: {finding.body}\n\n"
            f"Relevance: {relevance}. Investigate for patterns the fleet "
            f"should learn from — agent configuration, prompt design, "
            f"tool use, workflow structure.{context_str}"
        ),
        "tags": [_sanitize_tag(t) for t in finding.tags],
        "relevance": relevance,
    }


def _star_surge_entry(finding: Finding, data: dict) -> dict:
    """Brain PATTERN: Community validates an approach (peer review signal).

    Rapid star growth means the community is adopting this — it's peer
    validation that the pattern works. The Admiral should weight this
    higher when deciding what patterns to adopt in the fleet.
    """
    name = data.get("repo") or data.get("full_name", "unknown")
    delta = data.get("delta", 0)
    stars = data.get("stars", 0)

    return {
        "category": "pattern",
        "title": _sanitize_text(f"Community validates: {name} (+{delta:,} stars)"),
        "content": _sanitize_text(
            f"{name} gained {delta:,} stars (now {stars:,} total).\n\n"
            f"Rapid adoption signals the community validates this approach. "
            f"The Admiral should prioritize reviewing this for fleet-relevant "
            f"patterns — if many developers are adopting it, there's likely "
            f"something worth learning.\n\n{finding.body}"
        ),
        "tags": [_sanitize_tag(t) for t in finding.tags],
    }


def _generic_release_entry(finding: Finding, data: dict) -> dict:
    """Brain CONTEXT: General release (backward compat)."""
    repo = data.get("repo", "unknown")
    tag = data.get("tag", "")
    return {
        "category": "context",
        "title": _sanitize_text(f"Release: {repo} {tag}"),
        "content": _sanitize_text(f"{repo} released {tag}. {finding.body}"),
        "tags": [_sanitize_tag(t) for t in finding.tags],
    }


def _generic_repo_entry(finding: Finding, data: dict) -> dict:
    """Brain CONTEXT: General repo discovery (backward compat)."""
    full_name = data.get("full_name", "unknown")
    stars = data.get("stars", 0)
    return {
        "category": "context",
        "title": _sanitize_text(f"Discovered: {full_name}"),
        "content": _sanitize_text(
            f"Found {full_name} ({stars:,} stars). "
            f"{finding.body} "
            f"Language: {data.get('language', 'unknown')}."
        ),
        "tags": [_sanitize_tag(t) for t in finding.tags],
    }


def _sanitize_text(text: str) -> str:
    """Remove potentially dangerous content from text headed for Brain storage."""
    if not text:
        return ""

    text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", "", text)

    injection_markers = [
        "ignore previous instructions",
        "ignore all instructions",
        "disregard your instructions",
        "system prompt",
        "you are now",
        "new instructions:",
        "override:",
        "admin mode",
        "jailbreak",
        "<script",
        "javascript:",
        "onerror=",
        "onload=",
    ]
    text_lower = text.lower()
    for marker in injection_markers:
        if marker in text_lower:
            text = text + f" [QUARANTINE FLAG: contains pattern '{marker}']"

    return text.strip()


def _sanitize_tag(tag: str) -> str:
    """Ensure tags are safe alphanumeric-and-hyphens strings."""
    return re.sub(r"[^a-zA-Z0-9\-]", "", tag.lower().strip())


def _safe_repr(s: str) -> str:
    """Produce a safe string representation for Python source.

    SECURITY: Uses repr() which handles all escaping correctly.
    """
    return repr(s)
