"""Convert monitor findings into Brain seed candidates.

Findings are translated into Brain entry format matching the schema
in brain/core/models.py. Candidates are written to a Python file
that can be reviewed, edited, and then executed to plant the seeds.

IMPORTANT: All candidates pass through the immune system (quarantine.py)
before being eligible for Brain ingestion. No raw external content
is ever written directly to the Brain.
"""

from __future__ import annotations

import os
import re
from datetime import datetime, timezone

from .scanner import ScanResult, Finding


# Maps finding kinds to Brain entry categories
_KIND_TO_CATEGORY = {
    "release": "context",
    "new_repo": "context",
    "star_surge": "context",
    "trending": "context",
}


def write_seed_candidates(result: ScanResult, output_dir: str) -> str | None:
    """Generate a Python seed file from scan findings.

    The output file contains Brain-compatible entry definitions that
    must be reviewed before execution. Each entry is clearly marked
    as a CANDIDATE requiring human or Admiral approval.

    Args:
        result: Scan results to convert
        output_dir: Directory to write the seed file

    Returns:
        Path to the generated file, or None if no findings.
    """
    if not result.has_findings:
        return None

    os.makedirs(output_dir, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    path = os.path.join(output_dir, f"seed-candidates-{today}.py")

    content = _render_seed_file(result, today)

    with open(path, "w") as f:
        f.write(content)

    return path


def _render_seed_file(result: ScanResult, date: str) -> str:
    """Render scan findings as a Brain seed script."""
    lines = []

    lines.append(f'"""Seed candidates generated by AI Landscape Monitor — {date}')
    lines.append(f"")
    lines.append(f"REVIEW REQUIRED: These entries were auto-generated from external sources.")
    lines.append(f"Each entry must be reviewed for accuracy and relevance before planting.")
    lines.append(f"All entries will pass through quarantine validation before Brain ingestion.")
    lines.append(f"")
    lines.append(f"To plant approved seeds:")
    lines.append(f"    python -m aiStrat.monitor.seed_writer --plant {date}")
    lines.append(f'"""')
    lines.append(f"")
    lines.append(f"from __future__ import annotations")
    lines.append(f"")
    lines.append(f'SESSION = "monitor-{date}"')
    lines.append(f'PROJECT = "fleet-admiral"')
    lines.append(f"")
    lines.append(f"")
    lines.append(f"# Each candidate is a dict matching brain_record() parameters.")
    lines.append(f"# Set 'approved': True to include when planting.")
    lines.append(f"CANDIDATES = [")

    for i, finding in enumerate(result.findings):
        entry = _finding_to_entry(finding, i)
        if entry:
            lines.append(f"    # ── Candidate {i+1}: {finding.kind} ──")
            lines.append(f"    {{")
            lines.append(f'        "approved": False,  # Set to True after review')
            lines.append(f'        "project": PROJECT,')
            lines.append(f'        "category": "{entry["category"]}",')
            lines.append(f'        "title": {_safe_repr(entry["title"])},')
            lines.append(f'        "content": {_safe_repr(entry["content"])},')
            lines.append(f'        "metadata": {{')
            lines.append(f'            "tags": {entry["tags"]!r},')
            lines.append(f'            "source": "ai-landscape-monitor",')
            lines.append(f'            "scan_date": "{date}",')
            if finding.url:
                lines.append(f'            "url": {_safe_repr(finding.url)},')
            lines.append(f"        }},")
            lines.append(f'        "source_agent": "monitor",')
            lines.append(f'        "source_session": SESSION,')
            lines.append(f"    }},")

    lines.append(f"]")
    lines.append(f"")
    lines.append(f"")
    lines.append(f"def get_approved():")
    lines.append(f'    """Return only approved candidates."""')
    lines.append(f'    return [c for c in CANDIDATES if c.get("approved")]')
    lines.append(f"")

    return "\n".join(lines)


def _finding_to_entry(finding: Finding, index: int) -> dict | None:
    """Convert a Finding to a Brain entry dict."""
    category = _KIND_TO_CATEGORY.get(finding.kind, "context")
    data = finding.data

    if finding.kind == "release":
        repo = data.get("repo", "unknown")
        tag = data.get("tag", "")
        title = f"Release: {repo} {tag}"
        content = (
            f"{repo} released version {tag}. "
            f"{finding.body}"
        )
        tags = finding.tags

    elif finding.kind == "new_repo":
        full_name = data.get("full_name", "unknown")
        stars = data.get("stars", 0)
        title = f"New repository: {full_name}"
        content = (
            f"Discovered {full_name} ({stars:,} stars). "
            f"{finding.body} "
            f"Language: {data.get('language', 'unknown')}."
        )
        tags = finding.tags

    elif finding.kind == "star_surge":
        name = data.get("repo") or data.get("full_name", "unknown")
        delta = data.get("delta", 0)
        stars = data.get("stars", 0)
        title = f"Star surge: {name} (+{delta:,})"
        content = (
            f"{name} gained {delta:,} stars (now {stars:,} total). "
            f"Rapid growth signals increasing ecosystem adoption. "
            f"{finding.body}"
        )
        tags = finding.tags
        category = "pattern"  # Star surges indicate ecosystem shifts

    else:
        title = finding.title
        content = finding.body
        tags = finding.tags

    return {
        "category": category,
        "title": _sanitize_text(title),
        "content": _sanitize_text(content),
        "tags": [_sanitize_tag(t) for t in tags],
    }


def _sanitize_text(text: str) -> str:
    """Remove potentially dangerous content from text headed for Brain storage.

    This is a first-pass sanitization. The full immune system in quarantine.py
    provides deeper analysis before Brain ingestion.
    """
    if not text:
        return ""

    # Strip control characters except newlines and tabs
    text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", "", text)

    # Neutralize common injection patterns in data destined for LLM consumption
    # These patterns could manipulate agents that later read Brain entries
    injection_markers = [
        "ignore previous instructions",
        "ignore all instructions",
        "disregard your instructions",
        "system prompt",
        "you are now",
        "new instructions:",
        "override:",
        "admin mode",
        "jailbreak",
        "<script",
        "javascript:",
        "onerror=",
        "onload=",
    ]
    text_lower = text.lower()
    for marker in injection_markers:
        if marker in text_lower:
            # Don't silently remove — flag it
            text = text + f" [QUARANTINE FLAG: contains pattern '{marker}']"

    return text.strip()


def _sanitize_tag(tag: str) -> str:
    """Ensure tags are safe alphanumeric-and-hyphens strings."""
    return re.sub(r"[^a-zA-Z0-9\-]", "", tag.lower().strip())


def _safe_repr(s: str) -> str:
    """Produce a safe string representation for Python source.

    SECURITY: Uses repr() which handles all escaping correctly.
    Never construct Python string literals manually from untrusted input —
    the escape ordering is error-prone and can lead to code injection.
    """
    return repr(s)
